### ISSUE TITLE
Move to official org?

### ISSUE THREAD

**Issue by zenorocha** [dracula/terminator#1]
Hello!

I'm the creator of Dracula color scheme. I was searching for themes created by the community and I found yours. Good job by the way!

I was wondering if you are interested in transferring this repository to the official organization (https://github.com/dracula). You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

What do you think?

**Comment by OmarElebiary** [comment]
Hello!

@zenorocha
Yes, I am interested in transferring the repository to the official
organization.

**Comment by zenorocha** [comment]
Great! I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by zenorocha** [comment]
It's live! https://draculatheme.com/terminator 🎉
